name: Diff manifests against ref

on:
  workflow_call:
    inputs:
      path:
        type: string
        description: "Path to file or directory in which to look for manifests to diff (default: env)"
        default: env
      skipctl-version:
        type: string
        description: "Which version of `skipctl` to use (default: latest)"
        default: latest
      ref:
        type: string
        description: "Which git ref to compare agains (default: origin/main)"
        default: origin/main

jobs:
  diff-file:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          submodules: true
          persist-credentials: false

      - name: Install `skipctl` @ ${SKIPCTL_VERSION}
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: kartverket/skipctl
          tag: ${SKIPCTL_VERSION}
          cache: enable
        env:
          SKIPCTL_VERSION: ${{ inputs.skipctl-version }}

      - name: Run diff CLI against main
        shell: bash
        run: |
          set -euo pipefail

          # Function to generate diff output with individual file toggles
          generate_diff_output() {
              local pattern=$1
              local output=""

              # First find all directories matching the pattern, then find files in them
              while IFS= read -r -d '' dir; do
                  while IFS= read -r -d '' file; do
                      local diff_result
                      diff_result=$(skipctl manifests diff -p "$file" --ref ${INPUTS_REF} --diff-format patch 2>/dev/null || true)

                      if [ -n "$diff_result" ]; then
                          local file_path="$file"
                          # Remove the input path prefix for cleaner display
                          local display_path="${file_path#${INPUTS_PATH}/}"

                          output+="<details>"
                          output+=$'\n'
                          output+="  <summary><b>$display_path</b></summary>"
                          output+=$'\n'
                          output+=$'\n'
                          output+='```diff'
                          output+=$'\n'
                          output+="$diff_result"
                          output+=$'\n'
                          output+='```'
                          output+=$'\n'
                          output+="</details>"
                          output+=$'\n'
                      fi
                  done < <(find "$dir" -type f -print0 | sort -z)
              done < <(find ${INPUTS_PATH} -type d -name "$pattern" -print0 | sort -z)

              echo "$output"
          }

          DIFF_OUTPUT_PROD="$(generate_diff_output '*-prod')"
          DIFF_OUTPUT_DEV="$(generate_diff_output '*-dev')"

          {
              echo 'DIFF_OUTPUT_PROD<<EOF'
              printf '%s\n' "$DIFF_OUTPUT_PROD"
              echo 'EOF'
              echo 'DIFF_OUTPUT_DEV<<EOF'
              printf '%s\n' "$DIFF_OUTPUT_DEV"
              echo 'EOF'
          } >> "$GITHUB_ENV"
        env:
          INPUTS_REF: ${{ inputs.ref }}
          INPUTS_PATH: ${{ inputs.path }}

      # PROD comments
      - name: Post/Update PROD diff comment
        if: ${{ env.DIFF_OUTPUT_PROD != '' }}
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          comment-tag: prod-diff
          mode: upsert
          create-if-not-exists: true
          message: |
            > [!CAUTION]
            > <h1> Denne PR-en treffer produksjon.</h1>

            ${{ env.DIFF_OUTPUT_PROD }}

      - name: Delete PROD diff comment if empty
        if: ${{ env.DIFF_OUTPUT_PROD == '' }}
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          comment-tag: prod-diff
          mode: delete

      # DEV comments
      - name: Post/Update DEV diff comment
        if: ${{ env.DIFF_OUTPUT_DEV != '' }}
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          comment-tag: dev-diff
          mode: upsert
          create-if-not-exists: true
          message: |
            > [!NOTE]
            > <h1> Denne PR-en treffer:</h1>

            ${{ env.DIFF_OUTPUT_DEV }}

      - name: Delete DEV diff comment if empty
        if: ${{ env.DIFF_OUTPUT_DEV == '' }}
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          comment-tag: dev-diff
          mode: delete
